name: Build and Package

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  GO_VERSION: 1.16.5
  MAGE_VERSION: v1.11.0

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        uses: magefile/mage-action@v1
        with:
          version: ${{ env.MAGE_VERSION }}
          args: build
      - name: Test
        uses: magefile/mage-action@v1
        with:
          version: ${{ env.MAGE_VERSION }}
          args: test
      - name: Run
        shell: bash
        run: |
          if [[ ${{ runner.os }} = 'Windows' ]]; then
            export HOMEKEEPER=homekeeper.exe
          else
            export HOMEKEEPER=homekeeper
          fi
          cp ${{ github.workspace }}/$HOMEKEEPER ${{ runner.temp }}
          cd ${{ runner.temp }} && ./$HOMEKEEPER init --debug --git https://github.com/retiman/dotfiles.git
