name: Build and Package

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  GO_VERSION: 1.16.5

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Testing
        shell: pwsh
        run: |
          Write-Host "'${Env.GITHUB_API_URL}'"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --timeout 5m
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Run (Linux and MacOS)
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: |
          cp ${{ github.workspace }}/homekeeper ${{ runner.temp }}
          cd ${{ runner.temp }}
          ./homekeeper init --debug --git https://github.com/retiman/dotfiles.git
      - name: Run (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          Copy-Item ${{ github.workspace }}\homekeeper.exe ${{ runner.temp }}
          Set-Location ${{ runner.temp }}
          .\homekeeper.exe init --debug --git https://github.com/retiman/dotfiles.git
