name: Build and Package

on:
  pull_request:
  push:
    branchs: [ main ]

jobs:
  build:
    runs-on: [ linux ]
    steps:
      - uses: actions/checkout@v2
      - run: make dist
      - run: make test
