name: Build and Package

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.1

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Run (Linux and MacOS)
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: |
          cp ${{ github.workspace }}/homekeeper ${{ runner.temp }}
          cd ${{ runner.temp }}
          ./homekeeper init --debug --git https://github.com/retiman/dotfiles.git

      - name: Run (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          Copy-Item ${{ github.workspace }}\homekeeper.exe ${{ runner.temp }}
          Set-Location ${{ runner.temp }}
          .\homekeeper.exe init --debug --git https://github.com/retiman/dotfiles.git
