name: Build and Package

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.5
      - name: Format
        run: make format
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Test (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        continue-on-error: true
        run: |
          Remove-Item -Recurse -Force ./tmp
          mkdir ./tmp
          cd ./tmp
          ../homekeeper init --debug https://github.com/retiman/dotfiles.git
          ../homekeeper keep --debug
      - name: Test (Ubuntu & MacOS)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        shell: bash
        continue-on-error: true
        run: |
          rm -rf ./tmp
          mkdir ./tmp
          cd ./tmp
          ../homekeeper init --debug https://github.com/retiman/dotfiles.git
          ../homekeeper keep --debug
