name: Build and Package

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.5
      - name: Format
        run: make format
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Test (Ubuntu & MacOS)
        if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
        shell: bash
        run: |
          cd ${{ runner.temp }}
          $GITHUB_WORKSPACE/homekeeper init --debug --git https://github.com/retiman/dotfiles.git
          $GITHUB_WORKSPACE/homekeeper keep --debug
      - name: Test (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          cd ${{ runner.temp }}
          $Env:GITHUB_WORKSPACE\homekeeper.exe init --debug --git https://github.com/retiman/dotfiles.git
          $Env:GITHUB_WORKSPACE\homekeeper.exe keep --debug
