name: Format Code

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

      - name: Format
        run: make format

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@github.com
          message: Auto-format commit via GitHub Actions
        continue-on-error: true
