name: Release

on:
  pull_request:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>= 1.18.0'

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.1

      - name: Check
        run: make check

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          install-only: ${{ github.event_name == 'pull_request' }}
          distribution: goreleaser
          version: 1.8.3
          args: release --rm-dist
